networks:
  aondra:
    driver: bridge

services:
  ao.dashboard.postgres:
    container_name: 'ao.dashboard.postgres'
    image: 'postgres:15.8-alpine3.20'
    environment:
      POSTGRES_DB: ${DB_NAME:-mydatabase}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_USER: ${DB_USER:-myuser}
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    networks:
      - aondra
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-myuser} -d ${DB_NAME:-mydatabase}"]
      interval: 30s
      timeout: 10s
      retries: 5

  ao.dashboard.rabbitmq:
    container_name: 'ao.dashboard.rabbitmq'
    image: 'rabbitmq:4.0-rc-alpine'
    environment:
      RABBITMQ_DEFAULT_PASS: ${QUEUE_PASSWORD:-secret}
      RABBITMQ_DEFAULT_USER: ${QUEUE_USER:-myuser}
    ports:
      - "${FORWARD_QUEUE_PORT:-5672}:5672"
    networks:
      - aondra
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics check_port_listeners"]
      interval: 30s
      timeout: 10s
      retries: 5

  ao.dashboard.redis:
    container_name: 'ao.dashboard.redis'
    image: 'redis:7.4.0-alpine3.20'
    ports:
      - "${FORWARD_CACHE_PORT:-6379}:6379"
    networks:
      - aondra
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  ao.dashboard.node:
    container_name: ao.dashboard.node
    image: 'node:22.6.0-alpine3.20'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      NPM_CONFIG_LOGLEVEL: ${NPM_CONFIG_LOGLEVEL:-warn}
      NPM_CONFIG_PRODUCTION: ${NPM_CONFIG_PRODUCTION:-false}
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - .:/var/app
    working_dir: /var/app
    networks:
      - aondra
