spring:
  profiles:
    active: development
  application:
    name: Dashboard

logging:
  level:
    # OFF/ TRACE / DEBUG / INFO / WARN / ERROR / FATAL
    root: ${SPRING_LOG_LEVEL:ERROR}

pebble:
  suffix: .pebble
  cache: false

---
spring:
  config:
    activate:
      on-profile:
      - development

server:
  port: ${FORWARD_HTTP_PORT:8080}

---
spring:
  config:
    activate:
      on-profile:
      - production

server:
  port: 80

pebble:
  cache: true
