spring:
  profiles:
    active: development
  application:
    name: Dashboard

logging:
  level:
    # OFF/ TRACE / DEBUG / INFO / WARN / ERROR / FATAL
    root: ${SPRING_LOG_LEVEL:ERROR}

---
spring:
  profiles: development

server:
  port: ${FORWARD_HTTP_PORT:8080}

---
spring:
  profiles: production

server:
  port: 80
