FROM mcr.microsoft.com/devcontainers/base:debian-12

ARG JDK_VERSION_MAJOR=22
ARG JDK_VERSION_MINOR=0
ARG JDK_VERSION_PATCH=0
ARG JDK_VERSION_BUILD=1

ARG GRADLE_VERSION=8.9

# Install JDK
RUN cd /tmp;\
    BASE_URL="https://github.com/adoptium/temurin22-binaries/releases/download/jdk-${JDK_VERSION_MAJOR}.${JDK_VERSION_MINOR}.${JDK_VERSION_PATCH}%2B${JDK_VERSION_BUILD}";\
    TAR_FILE="OpenJDK${JDK_VERSION_MAJOR}U-jdk_x64_linux_hotspot_${JDK_VERSION_MAJOR}.${JDK_VERSION_MINOR}.${JDK_VERSION_PATCH}_${JDK_VERSION_BUILD}.tar.gz";\
    SIG_FILE="${TAR_FILE}.sig";\
    CHECKSUM_FILE="${TAR_FILE}.sha256.txt";\
    \
    wget ${BASE_URL}/${TAR_FILE} -O ${TAR_FILE}\
        || { echo "Failed to download OpenJDK\nURL: ${BASE_URL}/${TAR_FILE}" && exit 1; };\
    wget ${BASE_URL}/${SIG_FILE} -O ${SIG_FILE}\
        || { echo "Failed to download signature\nURL: ${BASE_URL}/${SIG_FILE}" && exit 1; };\
    wget ${BASE_URL}/${CHECKSUM_FILE} -O ${CHECKSUM_FILE}\
        || { echo "Failed to download checksum\nURL: ${BASE_URL}/${CHECKSUM_FILE}" && exit 1; };\
    \
    sha256sum -c ${CHECKSUM_FILE}\
        || { echo 'Checksum verification failed' && exit 1; };\
    \
    wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor -o /etc/apt/trusted.gpg.d/adoptium.gpg\
        || { echo 'Failed to download and import GPG key' && exit 1; };\
    \
    gpg --import /etc/apt/trusted.gpg.d/adoptium.gpg;\
    if ! gpg --list-keys | grep -iq "adoptium"; then\
        echo 'GPG key import failed: Adoptium key not found!' && exit 1;\
    fi;\
    gpg --verify ${SIG_FILE} ${TAR_FILE}\
        || { echo 'GPG signature verification failed' && exit 1; };\
    \
    mkdir -p /usr/local/lib/openjdk/${JDK_VERSION_MAJOR};\
    tar -xzf ${TAR_FILE} -C /usr/local/lib/openjdk/${JDK_VERSION_MAJOR} --strip-components=1;\
    rm ${TAR_FILE} ${SIG_FILE} ${CHECKSUM_FILE};\
    ln -s /usr/local/lib/openjdk/${JDK_VERSION_MAJOR}/bin/java /usr/bin/java

ENV JAVA_HOME=/usr/local/lib/openjdk/$JDK_VERSION
ENV PATH=$JAVA_HOME/bin:$PATH

# Install Gradle
RUN wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -O /tmp/gradle.zip;\
    unzip /tmp/gradle.zip -d /opt/gradle;\
    mv /opt/gradle/gradle-${GRADLE_VERSION} /opt/gradle/${GRADLE_VERSION};\
    rm /tmp/gradle.zip;\
    ln -s /opt/gradle/${GRADLE_VERSION}/bin/gradle /usr/bin/gradle

ENV GRADLE_HOME=/opt/gradle/${GRADLE_VERSION}
ENV PATH=$GRADLE_HOME/bin:$PATH

# clean up
RUN apt clean;\
    rm -rf /var/lib/apt/lists/*

# set up Fish as shell
RUN chsh -s /usr/bin/fish vscode
