FROM mcr.microsoft.com/devcontainers/base:debian-12

ARG JDK_VERSION_MAJOR=22
ARG JDK_VERSION_MINOR=0
ARG JDK_VERSION_PATCH=0
ARG JDK_VERSION_BUILD=1

ARG GRADLE_VERSION=8.9

# Install JDK
RUN wget https://github.com/adoptium/temurin22-binaries/releases/download/jdk-${JDK_VERSION_MAJOR}.${JDK_VERSION_MINOR}.${JDK_VERSION_PATCH}%2B${JDK_VERSION_BUILD}/OpenJDK${JDK_VERSION_MAJOR}U-jdk_x64_linux_hotspot_${JDK_VERSION_MAJOR}.${JDK_VERSION_MINOR}.${JDK_VERSION_PATCH}_${JDK_VERSION_BUILD}.tar.gz -O /tmp/openjdk.tar.gz;\
    mkdir -p /usr/local/lib/openjdk/${JDK_VERSION_MAJOR};\
    tar -xzf /tmp/openjdk.tar.gz -C /usr/local/lib/openjdk/${JDK_VERSION_MAJOR} --strip-components=1;\
    rm /tmp/openjdk.tar.gz;\
    ln -s /usr/local/lib/openjdk/${JDK_VERSION_MAJOR}/bin/java /usr/bin/java

ENV JAVA_HOME=/usr/local/lib/openjdk/$JDK_VERSION
ENV PATH=$JAVA_HOME/bin:$PATH

# Install Gradle
RUN wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -O /tmp/gradle.zip;\
    unzip /tmp/gradle.zip -d /opt/gradle;\
    mv /opt/gradle/gradle-${GRADLE_VERSION} /opt/gradle/${GRADLE_VERSION};\
    rm /tmp/gradle.zip;\
    ln -s /opt/gradle/${GRADLE_VERSION}/bin/gradle /usr/bin/gradle

ENV GRADLE_HOME=/opt/gradle/${GRADLE_VERSION}
ENV PATH=$GRADLE_HOME/bin:$PATH

# clean up
RUN apt clean;\
    rm -rf /var/lib/apt/lists/*

# set up Fish as shell
RUN chsh -s /usr/bin/fish vscode
